/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMirrorENSRegistrarInterface extends ethers.utils.Interface {
  functions: {
    "changeRootnodeOwner(address)": FunctionFragment;
    "register(string,address)": FunctionFragment;
    "updateENSReverseRegistrar()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "changeRootnodeOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateENSReverseRegistrar",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "changeRootnodeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateENSReverseRegistrar",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMirrorENSRegistrar extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMirrorENSRegistrarInterface;

  functions: {
    changeRootnodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeRootnodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateENSReverseRegistrar(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateENSReverseRegistrar()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  changeRootnodeOwner(
    newOwner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeRootnodeOwner(address)"(
    newOwner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  register(
    label_: string,
    owner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "register(string,address)"(
    label_: string,
    owner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateENSReverseRegistrar(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateENSReverseRegistrar()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    changeRootnodeOwner(
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeRootnodeOwner(address)"(
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    register(
      label_: string,
      owner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateENSReverseRegistrar(overrides?: CallOverrides): Promise<void>;

    "updateENSReverseRegistrar()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    changeRootnodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeRootnodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateENSReverseRegistrar(overrides?: Overrides): Promise<BigNumber>;

    "updateENSReverseRegistrar()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    changeRootnodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeRootnodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateENSReverseRegistrar(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateENSReverseRegistrar()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
