/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMirrorENSRegistrarInterface extends ethers.utils.Interface {
  functions: {
    "changeInviteToken(address)": FunctionFragment;
    "changeRootnodeOwner(address)": FunctionFragment;
    "getENS()": FunctionFragment;
    "getENSReverseRegistrar()": FunctionFragment;
    "isAvailable(bytes32)": FunctionFragment;
    "register(string,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "changeInviteToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeRootnodeOwner",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getENS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getENSReverseRegistrar",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAvailable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeInviteToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeRootnodeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getENS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getENSReverseRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;

  events: {};
}

export class IMirrorENSRegistrar extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMirrorENSRegistrarInterface;

  functions: {
    changeInviteToken(
      inviteToken_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeInviteToken(address)"(
      inviteToken_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    changeRootnodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeRootnodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getENS(overrides?: CallOverrides): Promise<[string]>;

    "getENS()"(overrides?: CallOverrides): Promise<[string]>;

    getENSReverseRegistrar(overrides?: CallOverrides): Promise<[string]>;

    "getENSReverseRegistrar()"(overrides?: CallOverrides): Promise<[string]>;

    isAvailable(
      subnode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isAvailable(bytes32)"(
      subnode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  changeInviteToken(
    inviteToken_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeInviteToken(address)"(
    inviteToken_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  changeRootnodeOwner(
    newOwner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeRootnodeOwner(address)"(
    newOwner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getENS(overrides?: CallOverrides): Promise<string>;

  "getENS()"(overrides?: CallOverrides): Promise<string>;

  getENSReverseRegistrar(overrides?: CallOverrides): Promise<string>;

  "getENSReverseRegistrar()"(overrides?: CallOverrides): Promise<string>;

  isAvailable(subnode_: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  "isAvailable(bytes32)"(
    subnode_: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  register(
    label_: string,
    owner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "register(string,address)"(
    label_: string,
    owner_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    changeInviteToken(
      inviteToken_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeInviteToken(address)"(
      inviteToken_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeRootnodeOwner(
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeRootnodeOwner(address)"(
      newOwner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getENS(overrides?: CallOverrides): Promise<string>;

    "getENS()"(overrides?: CallOverrides): Promise<string>;

    getENSReverseRegistrar(overrides?: CallOverrides): Promise<string>;

    "getENSReverseRegistrar()"(overrides?: CallOverrides): Promise<string>;

    isAvailable(
      subnode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isAvailable(bytes32)"(
      subnode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    register(
      label_: string,
      owner_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    changeInviteToken(
      inviteToken_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeInviteToken(address)"(
      inviteToken_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    changeRootnodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeRootnodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getENS(overrides?: CallOverrides): Promise<BigNumber>;

    "getENS()"(overrides?: CallOverrides): Promise<BigNumber>;

    getENSReverseRegistrar(overrides?: CallOverrides): Promise<BigNumber>;

    "getENSReverseRegistrar()"(overrides?: CallOverrides): Promise<BigNumber>;

    isAvailable(
      subnode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isAvailable(bytes32)"(
      subnode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    changeInviteToken(
      inviteToken_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeInviteToken(address)"(
      inviteToken_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    changeRootnodeOwner(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeRootnodeOwner(address)"(
      newOwner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getENS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getENS()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getENSReverseRegistrar(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getENSReverseRegistrar()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAvailable(
      subnode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAvailable(bytes32)"(
      subnode_: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "register(string,address)"(
      label_: string,
      owner_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
