/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MirrorENSReverseRegistrarInterface extends ethers.utils.Interface {
  functions: {
    "ADDR_REVERSE_NODE()": FunctionFragment;
    "claim(address)": FunctionFragment;
    "claimWithResolver(address,address)": FunctionFragment;
    "ens()": FunctionFragment;
    "node(address)": FunctionFragment;
    "resolver()": FunctionFragment;
    "setName(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ADDR_REVERSE_NODE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [string]): string;
  encodeFunctionData(
    functionFragment: "claimWithResolver",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "ens", values?: undefined): string;
  encodeFunctionData(functionFragment: "node", values: [string]): string;
  encodeFunctionData(functionFragment: "resolver", values?: undefined): string;
  encodeFunctionData(functionFragment: "setName", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "ADDR_REVERSE_NODE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimWithResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "node", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resolver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;

  events: {};
}

export class MirrorENSReverseRegistrar extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MirrorENSReverseRegistrarInterface;

  functions: {
    ADDR_REVERSE_NODE(overrides?: CallOverrides): Promise<[string]>;

    "ADDR_REVERSE_NODE()"(overrides?: CallOverrides): Promise<[string]>;

    claim(owner: string, overrides?: Overrides): Promise<ContractTransaction>;

    "claim(address)"(
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimWithResolver(
      owner: string,
      resolver: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimWithResolver(address,address)"(
      owner: string,
      resolver: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    ens(overrides?: CallOverrides): Promise<[string]>;

    "ens()"(overrides?: CallOverrides): Promise<[string]>;

    node(addr: string, overrides?: CallOverrides): Promise<[string]>;

    "node(address)"(addr: string, overrides?: CallOverrides): Promise<[string]>;

    resolver(overrides?: CallOverrides): Promise<[string]>;

    "resolver()"(overrides?: CallOverrides): Promise<[string]>;

    setName(name: string, overrides?: Overrides): Promise<ContractTransaction>;

    "setName(string)"(
      name: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  ADDR_REVERSE_NODE(overrides?: CallOverrides): Promise<string>;

  "ADDR_REVERSE_NODE()"(overrides?: CallOverrides): Promise<string>;

  claim(owner: string, overrides?: Overrides): Promise<ContractTransaction>;

  "claim(address)"(
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimWithResolver(
    owner: string,
    resolver: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimWithResolver(address,address)"(
    owner: string,
    resolver: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  ens(overrides?: CallOverrides): Promise<string>;

  "ens()"(overrides?: CallOverrides): Promise<string>;

  node(addr: string, overrides?: CallOverrides): Promise<string>;

  "node(address)"(addr: string, overrides?: CallOverrides): Promise<string>;

  resolver(overrides?: CallOverrides): Promise<string>;

  "resolver()"(overrides?: CallOverrides): Promise<string>;

  setName(name: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setName(string)"(
    name: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    ADDR_REVERSE_NODE(overrides?: CallOverrides): Promise<string>;

    "ADDR_REVERSE_NODE()"(overrides?: CallOverrides): Promise<string>;

    claim(owner: string, overrides?: CallOverrides): Promise<string>;

    "claim(address)"(owner: string, overrides?: CallOverrides): Promise<string>;

    claimWithResolver(
      owner: string,
      resolver: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "claimWithResolver(address,address)"(
      owner: string,
      resolver: string,
      overrides?: CallOverrides
    ): Promise<string>;

    ens(overrides?: CallOverrides): Promise<string>;

    "ens()"(overrides?: CallOverrides): Promise<string>;

    node(addr: string, overrides?: CallOverrides): Promise<string>;

    "node(address)"(addr: string, overrides?: CallOverrides): Promise<string>;

    resolver(overrides?: CallOverrides): Promise<string>;

    "resolver()"(overrides?: CallOverrides): Promise<string>;

    setName(name: string, overrides?: CallOverrides): Promise<string>;

    "setName(string)"(name: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ADDR_REVERSE_NODE(overrides?: CallOverrides): Promise<BigNumber>;

    "ADDR_REVERSE_NODE()"(overrides?: CallOverrides): Promise<BigNumber>;

    claim(owner: string, overrides?: Overrides): Promise<BigNumber>;

    "claim(address)"(owner: string, overrides?: Overrides): Promise<BigNumber>;

    claimWithResolver(
      owner: string,
      resolver: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claimWithResolver(address,address)"(
      owner: string,
      resolver: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    ens(overrides?: CallOverrides): Promise<BigNumber>;

    "ens()"(overrides?: CallOverrides): Promise<BigNumber>;

    node(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "node(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    resolver(overrides?: CallOverrides): Promise<BigNumber>;

    "resolver()"(overrides?: CallOverrides): Promise<BigNumber>;

    setName(name: string, overrides?: Overrides): Promise<BigNumber>;

    "setName(string)"(name: string, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ADDR_REVERSE_NODE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ADDR_REVERSE_NODE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(owner: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "claim(address)"(
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimWithResolver(
      owner: string,
      resolver: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimWithResolver(address,address)"(
      owner: string,
      resolver: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    ens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ens()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    node(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "node(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    resolver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "resolver()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setName(name: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "setName(string)"(
      name: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
