/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MirrorPublicationFactoryV1Interface extends ethers.utils.Interface {
  functions: {
    "createPublication(address,string,string,uint8)": FunctionFragment;
    "isInviteToken()": FunctionFragment;
    "mirrorInviteToken()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createPublication",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isInviteToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mirrorInviteToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createPublication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInviteToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mirrorInviteToken",
    data: BytesLike
  ): Result;

  events: {
    "PublicationCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PublicationCreated"): EventFragment;
}

export class MirrorPublicationFactoryV1 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MirrorPublicationFactoryV1Interface;

  functions: {
    createPublication(
      owner: string,
      tokenName: string,
      tokenSymbol: string,
      tokenDecimals: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createPublication(address,string,string,uint8)"(
      owner: string,
      tokenName: string,
      tokenSymbol: string,
      tokenDecimals: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isInviteToken(overrides?: CallOverrides): Promise<[boolean]>;

    "isInviteToken()"(overrides?: CallOverrides): Promise<[boolean]>;

    mirrorInviteToken(overrides?: CallOverrides): Promise<[string]>;

    "mirrorInviteToken()"(overrides?: CallOverrides): Promise<[string]>;
  };

  createPublication(
    owner: string,
    tokenName: string,
    tokenSymbol: string,
    tokenDecimals: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createPublication(address,string,string,uint8)"(
    owner: string,
    tokenName: string,
    tokenSymbol: string,
    tokenDecimals: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isInviteToken(overrides?: CallOverrides): Promise<boolean>;

  "isInviteToken()"(overrides?: CallOverrides): Promise<boolean>;

  mirrorInviteToken(overrides?: CallOverrides): Promise<string>;

  "mirrorInviteToken()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createPublication(
      owner: string,
      tokenName: string,
      tokenSymbol: string,
      tokenDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "createPublication(address,string,string,uint8)"(
      owner: string,
      tokenName: string,
      tokenSymbol: string,
      tokenDecimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isInviteToken(overrides?: CallOverrides): Promise<boolean>;

    "isInviteToken()"(overrides?: CallOverrides): Promise<boolean>;

    mirrorInviteToken(overrides?: CallOverrides): Promise<string>;

    "mirrorInviteToken()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    PublicationCreated(publication: null, owner: null): EventFilter;
  };

  estimateGas: {
    createPublication(
      owner: string,
      tokenName: string,
      tokenSymbol: string,
      tokenDecimals: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createPublication(address,string,string,uint8)"(
      owner: string,
      tokenName: string,
      tokenSymbol: string,
      tokenDecimals: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isInviteToken(overrides?: CallOverrides): Promise<BigNumber>;

    "isInviteToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    mirrorInviteToken(overrides?: CallOverrides): Promise<BigNumber>;

    "mirrorInviteToken()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createPublication(
      owner: string,
      tokenName: string,
      tokenSymbol: string,
      tokenDecimals: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createPublication(address,string,string,uint8)"(
      owner: string,
      tokenName: string,
      tokenSymbol: string,
      tokenDecimals: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isInviteToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isInviteToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mirrorInviteToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "mirrorInviteToken()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
