/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SplitterInterface extends ethers.utils.Interface {
  functions: {
    "accounts(uint256)": FunctionFragment;
    "amountFromPercent(uint256,uint32)": FunctionFragment;
    "initialize(address[],uint32[])": FunctionFragment;
    "percentages(uint256)": FunctionFragment;
    "splitETH()": FunctionFragment;
    "splitToken(address)": FunctionFragment;
    "validate()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "amountFromPercent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "percentages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "splitETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "splitToken", values: [string]): string;
  encodeFunctionData(functionFragment: "validate", values?: undefined): string;

  decodeFunctionResult(functionFragment: "accounts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "amountFromPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "percentages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "splitETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "splitToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;

  events: {
    "TransferETH(address,uint256,uint32,bool)": EventFragment;
    "TransferToken(address,address,uint256,uint32,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TransferETH"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferToken"): EventFragment;
}

export class Splitter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SplitterInterface;

  functions: {
    accounts(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "accounts(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    amountFromPercent(
      amount: BigNumberish,
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "amountFromPercent(uint256,uint32)"(
      amount: BigNumberish,
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initialize(
      accounts_: string[],
      percentages_: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address[],uint32[])"(
      accounts_: string[],
      percentages_: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    percentages(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    "percentages(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    splitETH(overrides?: Overrides): Promise<ContractTransaction>;

    "splitETH()"(overrides?: Overrides): Promise<ContractTransaction>;

    splitToken(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "splitToken(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    validate(
      overrides?: CallOverrides
    ): Promise<[boolean] & { isValid: boolean }>;

    "validate()"(
      overrides?: CallOverrides
    ): Promise<[boolean] & { isValid: boolean }>;
  };

  accounts(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "accounts(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  amountFromPercent(
    amount: BigNumberish,
    percent: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "amountFromPercent(uint256,uint32)"(
    amount: BigNumberish,
    percent: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  initialize(
    accounts_: string[],
    percentages_: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address[],uint32[])"(
    accounts_: string[],
    percentages_: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  percentages(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

  "percentages(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  splitETH(overrides?: Overrides): Promise<ContractTransaction>;

  "splitETH()"(overrides?: Overrides): Promise<ContractTransaction>;

  splitToken(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "splitToken(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  validate(overrides?: CallOverrides): Promise<boolean>;

  "validate()"(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    accounts(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "accounts(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    amountFromPercent(
      amount: BigNumberish,
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "amountFromPercent(uint256,uint32)"(
      amount: BigNumberish,
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      accounts_: string[],
      percentages_: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address[],uint32[])"(
      accounts_: string[],
      percentages_: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    percentages(arg0: BigNumberish, overrides?: CallOverrides): Promise<number>;

    "percentages(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    splitETH(overrides?: CallOverrides): Promise<boolean>;

    "splitETH()"(overrides?: CallOverrides): Promise<boolean>;

    splitToken(token: string, overrides?: CallOverrides): Promise<boolean>;

    "splitToken(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    validate(overrides?: CallOverrides): Promise<boolean>;

    "validate()"(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    TransferETH(
      account: null,
      amount: null,
      percent: null,
      success: null
    ): EventFilter;

    TransferToken(
      token: null,
      account: null,
      amount: null,
      percent: null,
      success: null
    ): EventFilter;
  };

  estimateGas: {
    accounts(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "accounts(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    amountFromPercent(
      amount: BigNumberish,
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "amountFromPercent(uint256,uint32)"(
      amount: BigNumberish,
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      accounts_: string[],
      percentages_: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address[],uint32[])"(
      accounts_: string[],
      percentages_: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    percentages(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "percentages(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    splitETH(overrides?: Overrides): Promise<BigNumber>;

    "splitETH()"(overrides?: Overrides): Promise<BigNumber>;

    splitToken(token: string, overrides?: Overrides): Promise<BigNumber>;

    "splitToken(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    validate(overrides?: CallOverrides): Promise<BigNumber>;

    "validate()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    accounts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "accounts(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    amountFromPercent(
      amount: BigNumberish,
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "amountFromPercent(uint256,uint32)"(
      amount: BigNumberish,
      percent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      accounts_: string[],
      percentages_: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address[],uint32[])"(
      accounts_: string[],
      percentages_: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    percentages(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "percentages(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    splitETH(overrides?: Overrides): Promise<PopulatedTransaction>;

    "splitETH()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    splitToken(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "splitToken(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    validate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "validate()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
