/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IMirrorPublicationFactoryV1 } from "../IMirrorPublicationFactoryV1";

export class IMirrorPublicationFactoryV1__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMirrorPublicationFactoryV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMirrorPublicationFactoryV1;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "string",
        name: "label",
        type: "string",
      },
      {
        internalType: "string",
        name: "tokenName",
        type: "string",
      },
      {
        internalType: "string",
        name: "tokenSymbol",
        type: "string",
      },
      {
        internalType: "uint8",
        name: "tokenDecimals",
        type: "uint8",
      },
    ],
    name: "createPublication",
    outputs: [
      {
        internalType: "address",
        name: "publication",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
