/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { OurStorage } from "../OurStorage";

export class OurStorage__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<OurStorage> {
    return super.deploy(overrides || {}) as Promise<OurStorage>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): OurStorage {
    return super.attach(address) as OurStorage;
  }
  connect(signer: Signer): OurStorage__factory {
    return super.connect(signer) as OurStorage__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OurStorage {
    return new Contract(address, _abi, signerOrProvider) as OurStorage;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "balanceForWindow",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentWindow",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "merkleRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "weth",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061011b806100206000396000f3fe6080604052348015600f57600080fd5b506004361060465760003560e01c80632eb4a7ab14604b5780633fc8cef314606657806381e580d3146097578063ba0bafb41460a6575b600080fd5b605360005481565b6040519081526020015b60405180910390f35b608073c778417e063141139fce010982780140aa0cd5ab81565b6040516001600160a01b039091168152602001605d565b605360a236600460ce565b60ae565b605360015481565b6003818154811060bd57600080fd5b600091825260209091200154905081565b60006020828403121560de578081fd5b503591905056fea26469706673582212206f598eebec6d77d71de896e72856091d564cb7512faadd7ae5b18b3ddb9d541864736f6c63430008040033";
