/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { SplitProxy } from "../SplitProxy";

export class SplitProxy__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<SplitProxy> {
    return super.deploy(overrides || {}) as Promise<SplitProxy>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SplitProxy {
    return super.attach(address) as SplitProxy;
  }
  connect(signer: Signer): SplitProxy__factory {
    return super.connect(signer) as SplitProxy__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SplitProxy {
    return new Contract(address, _abi, signerOrProvider) as SplitProxy;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "currentWindow",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "merkleRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "splitter",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50336001600160a01b0316633cd8045e6040518163ffffffff1660e01b8152600401602060405180830381600087803b15801561004c57600080fd5b505af1158015610060573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061008491906101be565b600360006101000a8154816001600160a01b0302191690836001600160a01b03160217905550336001600160a01b0316634f0e0ef36040518163ffffffff1660e01b8152600401602060405180830381600087803b1580156100e557600080fd5b505af11580156100f9573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061011d91906101be565b600260006101000a8154816001600160a01b0302191690836001600160a01b03160217905550336001600160a01b0316632eb4a7ab6040518163ffffffff1660e01b8152600401602060405180830381600087803b15801561017e57600080fd5b505af1158015610192573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101b691906101ec565b600055610204565b6000602082840312156101cf578081fd5b81516001600160a01b03811681146101e5578182fd5b9392505050565b6000602082840312156101fd578081fd5b5051919050565b610123806102136000396000f3fe60806040526004361060335760003560e01c80632eb4a7ab14607f5780633cd8045e1460a6578063ba0bafb41460d9576039565b36603957005b6000605960035473ffffffffffffffffffffffffffffffffffffffff1690565b905060405136600082376000803683855af43d806000843e818015607b578184f35b8184fd5b348015608a57600080fd5b50609360005481565b6040519081526020015b60405180910390f35b34801560b157600080fd5b5060035460405173ffffffffffffffffffffffffffffffffffffffff9091168152602001609d565b34801560e457600080fd5b5060936001548156fea26469706673582212207f370a0d2f87b7e05a71917a1e1d1a4485ad91634028bcc60afc3139227539ec64736f6c63430008030033";
